# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71a547d1715e133fddbfcec803d6368415a30c26471bd2e8db6fb66ad036b63a52d1592165b576677c3e9a47ba9b29c2921d02703250f28f788a7caf183e8f60

test:
  secret_key_base: 9c25a93a695ef3f493242730df2add3d25951133b9f47d45d3a207215717ae41c88cc83d3411fdb493981400095e76a4cd1248f224f65e387da54a4864bfe95d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
